CREATE TABLE IF NOT EXISTS valuterate
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    digitcode  Integer                                 NOT NULL,
    chcode     Character varying(20)                   NOT NULL,
    valutename Character varying(150)                  NOT NULL,
    quantity   Integer                                 NOT NULL,
    rate       Integer                                 NOT NULL,
    curdate    Date                                    NOT NULL,
    CONSTRAINT pk_valuterate PRIMARY KEY (id)
);
